FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    protobuf-compiler libprotobuf-dev libssl-dev pkg-config clang \
    iptables iproute2 curl ca-certificates \
    perl make \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
