use serde::{Deserialize, Serialize};

use crate::tunnel::proposal::{AttestProposal, Model};
use crate::tunnel::provider::ProviderType;

pub mod header;
pub mod metadata;
pub mod userdata;

/// Request structure for the key configuration endpoint
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
#[serde(deny_unknown_fields)]
pub struct KeyConfigRequest {
    /// One proposal per verifier the client holds; empty when it does not verify the server
    #[serde(default)]
    pub proposals: Vec<AttestProposal>,
}

/// Response structure for the key configuration endpoint
#[derive(Serialize, Deserialize, Debug)]
pub struct KeyConfigResponse {
    /// HPKE (Hybrid Public Key Encryption) key configuration
    pub hpke_key_config: HpkeKeyConfig,

    /// Attestation information - can be either an attestation result (passport model)
    /// or evidence (background check model)
    pub attestation_info: Option<ServerAttestationInfo>,
}

/// HPKE key configuration structure
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct HpkeKeyConfig {
    /// Expiration timestamp for this configuration
    pub expire_timestamp: u64,

    /// A base64 encoded list of key configurations, each entry is a Individual key configuration entry. Defined in Section 3.1 of RFC 9458.
    pub encoded_key_config_list: String,
}

/// Enum to differentiate between passport model and background check model
/// for attestation information in the key configuration response
#[derive(Serialize, Deserialize, Debug)]
#[serde(rename_all = "snake_case", tag = "model")]
pub enum ServerAttestationInfo {
    /// Passport model - server provides attestation result
    Passport {
        /// A JWT string representing the server's own Attestation Result
        /// This is used only in Client verification + passport model scenario
        attestation_result: String,
        /// Which AS/token provider produced `attestation_result`
        provider: ProviderType,
    },

    /// Background check model - server provides evidence
    BackgroundCheck {
        /// Evidence data containing the nonce
        /// This is used only in Client verification + background check model scenario
        evidence: serde_json::Value,
        /// Which provider the `evidence` JSON belongs to
        provider: ProviderType,
    },
}

impl ServerAttestationInfo {
    pub fn key(&self) -> (Model, ProviderType) {
        match self {
            Self::Passport { provider, .. } => (Model::Passport, *provider),
            Self::BackgroundCheck { provider, .. } => (Model::BackgroundCheck, *provider),
        }
    }
}

/// Query of the attestation challenge endpoint
#[derive(Serialize, Deserialize, Debug)]
pub struct AttestationChallengeQuery {
    /// Provider of the client's attester, naming the converter that must mint the nonce
    pub provider: ProviderType,
}

/// Response structure for the attestation challenge endpoint
#[derive(Serialize, Deserialize, Debug)]
pub struct AttestationChallengeResponse {
    /// A JWT string containing the challenge token
    pub challenge_token: String,
}

/// Request structure for the attestation verification endpoint
#[derive(Serialize, Deserialize, Debug)]
pub struct AttestationVerifyRequest {
    /// Evidence data containing the nonce
    pub evidence: serde_json::Value,
    /// Which provider the `evidence` JSON belongs to
    pub provider: ProviderType,
}

/// Response structure for the attestation verification endpoint
#[derive(Serialize, Deserialize, Debug)]
pub struct AttestationVerifyResponse {
    /// The attestation result JWT generated by the Attestation Service
    pub attestation_result: String,
    /// Which AS/token provider produced `attestation_result`
    pub provider: ProviderType,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn key_config_request_wire_shape() {
        let req: KeyConfigRequest = serde_json::from_value(json!({
            "proposals": [{"model": "passport", "provider": "ita"}]
        }))
        .unwrap();
        assert_eq!(
            req.proposals,
            vec![AttestProposal::Passport {
                provider: ProviderType::Ita
            }]
        );
        assert!(serde_json::from_value::<KeyConfigRequest>(json!({}))
            .unwrap()
            .proposals
            .is_empty());
        // A client from before proposals existed must not be mistaken for one that verifies nothing.
        assert!(serde_json::from_value::<KeyConfigRequest>(
            json!({"attestation_request": {"model": "passport"}})
        )
        .is_err());
    }

    #[test]
    fn provider_is_required() {
        assert!(serde_json::from_value::<ServerAttestationInfo>(
            json!({"model": "passport", "attestation_result": "jwt"})
        )
        .is_err());
        assert!(
            serde_json::from_value::<AttestationVerifyRequest>(json!({"evidence": {}})).is_err()
        );
        assert!(serde_json::from_value::<AttestationVerifyResponse>(
            json!({"attestation_result": "jwt"})
        )
        .is_err());
    }
}
